name: metronome_hub
description: Landing page + metronome demo
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  soundpool: ^2.4.1          # low-latency SFX playback
  google_fonts: ^6.2.1
  audioplayers: ^6.5.1
  http: ^1.2.0
  file_picker: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tick.wav
    - assets/tock.wav
